-- guftagu.ai — Supabase schema
-- Run this in the Supabase SQL editor (or via `supabase db push` if using CLI).
--
-- Design notes:
--  * businesses.id mirrors auth.users.id (1:1). One human login = one business account.
--  * The chat widget is public, so all widget writes go through the service-role key
--    server-side; RLS below only governs what the logged-in business can read.
--  * chats.visitor_id is an anonymous id generated by the widget (localStorage),
--    so no customer PII is required to use the widget.

-- ===================== tables =====================

create table if not exists public.businesses (
  id uuid primary key references auth.users (id) on delete cascade,
  company_name text not null,
  escalation_email text not null,
  widget_config jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.documents (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses (id) on delete cascade,
  filename text not null,
  content_type text not null,              -- 'text/plain' | 'application/pdf'
  size_bytes integer not null default 0,
  chunk_count integer not null default 0,
  status text not null default 'processing'
    check (status in ('processing', 'ready', 'failed')),
  error text,
  created_at timestamptz not null default now()
);

create table if not exists public.chats (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses (id) on delete cascade,
  visitor_id text not null,                -- anonymous, widget-generated
  language text,                           -- 'ur' | 'roman-ur' (detected at runtime)
  status text not null default 'active'
    check (status in ('active', 'flagged', 'escalated')),
  escalation_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated always as identity primary key,
  chat_id uuid not null references public.chats (id) on delete cascade,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  confidence numeric,                      -- 0..1, assistant turns only
  retrieved_chunks jsonb,                  -- snapshot of matched chunks: [{text, score, doc}]
  created_at timestamptz not null default now()
);

-- ===================== indexes =====================

create index if not exists documents_business_idx
  on public.documents (business_id, created_at desc);
create index if not exists chats_business_idx
  on public.chats (business_id, created_at desc);
create index if not exists messages_chat_idx
  on public.messages (chat_id, created_at);

-- ===================== updated_at trigger =====================

create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end $$;

drop trigger if exists chats_touch on public.chats;
create trigger chats_touch
  before update on public.chats
  for each row execute function public.touch_updated_at();

-- ===================== row level security =====================
-- businesses.id = auth.uid(), so "own row" checks are direct.

alter table public.businesses enable row level security;
alter table public.documents  enable row level security;
alter table public.chats      enable row level security;
alter table public.messages   enable row level security;

create policy "businesses: own row" on public.businesses
  for all using (auth.uid() = id) with check (auth.uid() = id);

create policy "documents: own business" on public.documents
  for all using (auth.uid() = business_id) with check (auth.uid() = business_id);

create policy "chats: own business" on public.chats
  for all using (auth.uid() = business_id) with check (auth.uid() = business_id);

create policy "messages: chats of own business" on public.messages
  for select using (
    exists (
      select 1 from public.chats c
      where c.id = messages.chat_id and c.business_id = auth.uid()
    )
  );
